[package]
name = "maa-utils"
version = "0.1.0"
authors = ["Loong Wang <wangl-cc@outlook.com>"]
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
