name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Lint (clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Lint (rustfmt)
        run: cargo fmt --all --check

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build maa-updater
        run: cargo build --bin maa-updater
      - name: Install MaaCore with maa-updater
        run: cargo run --bin maa-updater -- stable
      - name: Build maa-cli
        run: cargo build --bin maa-cli
      - name: Install cargo nextest
        run: cargo install cargo-nextest
      - name: Test
        run: cargo nextest run --all-targets --all-features -- --nocapture
      - name: Try to run maa-cli
        run: cargo run --bin maa-cli -- version
